language: rust
sudo: false


os: linux
rust: stable

cache: cargo

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (cargo install mdbook mdbook-linkcheck || echo "installed")
  - cargo install-update -a

script:
  - mdbook build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  local_dir: book/html
  on:
    branch: master
